---
title: "Reproducible Document"
author: "rostools" 
format: html
---

```{r setup}

library(tidyverse)

#| message: false 
#| warning: false 

post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))
```

```{r}
2+2
```
## About me 

- Katrine Bovién Gørlitz 
- Medicinsk Diagnostic Center 
- Central Denmark Hosiptal Region 

I am doing a *PhD* in **Diabetes Technology** 

## Simple code 
```{r}
3*3
```

## Testing for Git

## Showing the data 
```{r}
post_meal_data

glimpse(post_meal_data)
```

## Plot one continuous variable 

```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x=BMI)) + geom_histogram(bins=20)
```

See @fig-bmi-histo


## Exercise: discrete plots

```{r}
#| fig-cap: "Distribution of glykemi"
#| label: fig-glykemi-histo
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```

See @fig-glykemi-histo above for a cool plot!


## Exercise: Plotting two discrete variables 

```{r}

ggplot(post_meal_data, aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())

```
